// lib/icons/lucide.ts
import {
  ArrowUp, ArrowDown, ArrowLeft, ArrowRight,
  ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
  CornerUpLeft, CornerUpRight, CornerDownLeft, CornerDownRight,
  ChevronsUp, ChevronsDown, ChevronsLeft, ChevronsRight,
  ArrowUpRight, ArrowUpLeft, ArrowDownRight, ArrowDownLeft,
  ArrowUpFromLine, ArrowDownFromLine, ArrowLeftRight, ArrowUpDown,
  Move, RefreshCw, RotateCw, RotateCcw,
  Repeat, Workflow,
  File, FileText, FilePlus, FileMinus, FileCheck, FileX,
  FileCode, FileCode2, FileTerminal, FileWarning, FileScan, FileSignal, FileDiff, FileDigit, FileDown,
  Folder, FolderOpen, FolderPlus, FolderMinus, FolderSync,
  Image, Images, FileImage, Upload, Download, UploadCloud, DownloadCloud,
  Copy, Clipboard, ClipboardCheck, ClipboardCopy, ClipboardList, ClipboardPaste, Archive, Package,
  FileBox, FileStack, FileClock,
  User, Users, UserPlus, UserMinus, UserCheck, UserX,
  UserCog, UserCog2, Shield, ShieldCheck, ShieldAlert, ShieldOff,
  ShieldCog, ShieldPlus, ShieldMinus, Lock, Unlock, Key,
  Square, SquareCheck, CheckSquare, XSquare, MinusSquare, PlusSquare,
  Triangle, Circle, Hexagon, Octagon, Pentagon, Cross,
  TriangleAlert, CircleAlert, OctagonAlert, AlertTriangle, AlertCircle,
  Play, Pause, SkipBack, SkipForward, Rewind, FastForward,
  Volume, Volume1, Volume2, VolumeX,
  Maximize, Minimize, ZoomIn, ZoomOut, Focus,
  Sliders, SlidersHorizontal, SlidersVertical,
  Home, Settings, Search, Menu, Grid, List,
  MoreHorizontal, MoreVertical,
  X, Check, CheckCircle, Plus, Minus, CircleDot,
  Crosshair, MousePointer, Pointer,
  Cpu, Microchip, Monitor, Server, HardDrive, Printer, Tablet,
  Smartphone, Laptop, Computer, Keyboard, Mouse,
  Wifi, WifiOff, WifiCog, Plug, Plug2, PlugZap, Unplug,
  Battery, BatteryCharging, BatteryFull, BatteryLow, BatteryMedium, BatteryWarning, BatteryPlus,
  Usb, EthernetPort, HdmiPort,
  Radar, Tv, Radio, RadioReceiver,
  Thermometer, ThermometerSnowflake, ThermometerSun,
  Droplet, Wind, Waves, WavesArrowDown, WavesArrowUp,
  Flame, Zap, Bolt, Power, PowerCircle, PowerOff, CirclePower,
  Eye, EyeOff, Scan, ScanLine, ScanBarcode, ScanQrCode, ScanEye, ScanSearch,
  Signal, SignalHigh, SignalLow, SignalMedium, SignalZero, Activity,
  Gauge, GaugeCircle, CircleGauge,
  Divide, Equal, Percent, Hash, Sigma, Pi, Ampersand,
  Aperture,
  BarChart, BarChart2, BarChart3, BarChart4,
  BarChartHorizontal, BarChartBig,
  LineChart, PieChart, AreaChart, ScatterChart,
  ChartNoAxesCombined, ChartSpline,
  ChartColumn, ChartColumnIncreasing, ChartColumnDecreasing, ChartColumnStacked,
  ChartBar, ChartBarIncreasing, ChartBarDecreasing, ChartBarStacked,
  ChartLine, ChartPie, ChartArea, ChartScatter,
  ChartGantt, ChartNetwork, ChartNoAxesColumn,
  TrendingUp, TrendingDown,
  GanttChart, GanttChartSquare, CandlestickChart,
  FlaskConical, Beaker, TestTube, TestTube2, TestTubes, TestTubeDiagonal,
  Atom, Dna, Microscope, Telescope,
  Magnet, Pipette,
  Factory, Warehouse, Container, Boxes, Box,
  Forklift, Truck, TruckElectric,
  Wrench, Hammer, Drill, Toolbox, ToolCase,
  Cog, CircuitBoard,
  Cable, CableCar,
  SolarPanel,
  Bell, BellRing, BellOff, BellDot, BellElectric, Siren, AlarmClock,
  AlarmClockCheck, AlarmClockPlus, AlarmClockMinus, AlarmClockOff,
  AlarmCheck, AlarmPlus, AlarmMinus, AlarmSmoke,
  Lightbulb, LightbulbOff, Lamp, LampCeiling, LampDesk, LampFloor, LampWallDown, LampWallUp,
  Flashlight, FlashlightOff, Spotlight,
  Antenna, Satellite, SatelliteDish, RadioTower, Orbit,
  Barcode, QrCode,
  Radiation, Biohazard, FireExtinguisher,
  ShieldBan, ShieldClose,
  DoorClosed, DoorClosedLocked,
  PanelBottom, PanelBottomClose, PanelBottomOpen,
  PanelLeft, PanelLeftClose, PanelLeftOpen,
  PanelRight, PanelRightClose, PanelRightOpen,
  PanelTop, PanelTopClose, PanelTopOpen,
  LayoutDashboard, LayoutPanelLeft, LayoutPanelTop,
  Database, DatabaseBackup, DatabaseSearch,
  ServerCog, MonitorCog, MonitorCloud, MonitorDot, MonitorCheck,
  Cloud, CloudAlert, CloudBackup, CloudCheck, CloudCog, CloudDownload, CloudUpload, CloudSync, CloudOff,
  Terminal, TerminalSquare, Shell, Command,
  Code, Code2, CodeXml, CodeSquare,
  Binary,
  Map, MapPin, MapPinned, MapPlus, MapMinus, Compass,
  Clock, ClockAlert, ClockCheck, Timer, TimerOff, TimerReset,
  CalendarClock, CalendarCog, History,
  Layers, Layers2, Layers3, Component,
  Mail, Inbox, MessageCircle, MessageSquare,
  Phone, PhoneCall, PhoneIncoming, PhoneOutgoing,
  Send, AtSign,
  Video, VideoOff, Camera, CameraOff,
  Music, Headphones, Speaker, Mic, MicOff,
  Network, Router, Bluetooth, BluetoothConnected, BluetoothOff, BluetoothSearching,
  TowerControl, ParkingMeter,
  Stamp, PenTool,
  Logs, LogIn, LogOut,
  Recycle,
  MemoryStick,
  BriefcaseConveyorBelt, InspectionPanel,
  BrainCircuit, BrainCog,
  SquircleDashed,
  Microwave, WashingMachine,
  Diameter, SquareTerminal,
  SquareStack,
  Pin, PinOff,
  BoxSelect,
  BoomBox,
  HousePlug,
} from 'lucide-react'

export const LUCIDE_MAP = {
  ArrowUp, ArrowDown, ArrowLeft, ArrowRight,
  ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
  CornerUpLeft, CornerUpRight, CornerDownLeft, CornerDownRight,
  ChevronsUp, ChevronsDown, ChevronsLeft, ChevronsRight,
  ArrowUpRight, ArrowUpLeft, ArrowDownRight, ArrowDownLeft,
  ArrowUpFromLine, ArrowDownFromLine, ArrowLeftRight, ArrowUpDown,
  Move, RefreshCw, RotateCw, RotateCcw,
  Repeat, Workflow,
  File, FileText, FilePlus, FileMinus, FileCheck, FileX,
  FileCode, FileCode2, FileTerminal, FileWarning, FileScan, FileSignal, FileDiff, FileDigit, FileDown,
  Folder, FolderOpen, FolderPlus, FolderMinus, FolderSync,
  Image, Images, FileImage, Upload, Download, UploadCloud, DownloadCloud,
  Copy, Clipboard, ClipboardCheck, ClipboardCopy, ClipboardList, ClipboardPaste, Archive, Package,
  FileBox, FileStack, FileClock,
  User, Users, UserPlus, UserMinus, UserCheck, UserX,
  UserCog, UserCog2, Shield, ShieldCheck, ShieldAlert, ShieldOff,
  ShieldCog, ShieldPlus, ShieldMinus, Lock, Unlock, Key,
  Square, SquareCheck, CheckSquare, XSquare, MinusSquare, PlusSquare,
  Triangle, Circle, Hexagon, Octagon, Pentagon, Cross,
  TriangleAlert, CircleAlert, OctagonAlert, AlertTriangle, AlertCircle,
  Play, Pause, SkipBack, SkipForward, Rewind, FastForward,
  Volume, Volume1, Volume2, VolumeX,
  Maximize, Minimize, ZoomIn, ZoomOut, Focus,
  Sliders, SlidersHorizontal, SlidersVertical,
  Home, Settings, Search, Menu, Grid, List,
  MoreHorizontal, MoreVertical,
  X, Check, CheckCircle, Plus, Minus, CircleDot,
  Crosshair, MousePointer, Pointer,
  Cpu, Microchip, Monitor, Server, HardDrive, Printer, Tablet,
  Smartphone, Laptop, Computer, Keyboard, Mouse,
  Wifi, WifiOff, WifiCog, Plug, Plug2, PlugZap, Unplug,
  Battery, BatteryCharging, BatteryFull, BatteryLow, BatteryMedium, BatteryWarning, BatteryPlus,
  Usb, EthernetPort, HdmiPort,
  Radar, Tv, Radio, RadioReceiver,
  Thermometer, ThermometerSnowflake, ThermometerSun,
  Droplet, Wind, Waves, WavesArrowDown, WavesArrowUp,
  Flame, Zap, Bolt, Power, PowerCircle, PowerOff, CirclePower,
  Eye, EyeOff, Scan, ScanLine, ScanBarcode, ScanQrCode, ScanEye, ScanSearch,
  Signal, SignalHigh, SignalLow, SignalMedium, SignalZero, Activity,
  Gauge, GaugeCircle, CircleGauge,
  Divide, Equal, Percent, Hash, Sigma, Pi, Ampersand,
  Aperture,
  BarChart, BarChart2, BarChart3, BarChart4,
  BarChartHorizontal, BarChartBig,
  LineChart, PieChart, AreaChart, ScatterChart,
  ChartNoAxesCombined, ChartSpline,
  ChartColumn, ChartColumnIncreasing, ChartColumnDecreasing, ChartColumnStacked,
  ChartBar, ChartBarIncreasing, ChartBarDecreasing, ChartBarStacked,
  ChartLine, ChartPie, ChartArea, ChartScatter,
  ChartGantt, ChartNetwork, ChartNoAxesColumn,
  TrendingUp, TrendingDown,
  GanttChart, GanttChartSquare, CandlestickChart,
  FlaskConical, Beaker, TestTube, TestTube2, TestTubes, TestTubeDiagonal,
  Atom, Dna, Microscope, Telescope,
  Magnet, Pipette,
  Factory, Warehouse, Container, Boxes, Box,
  Forklift, Truck, TruckElectric,
  Wrench, Hammer, Drill, Toolbox, ToolCase,
  Cog, CircuitBoard,
  Cable, CableCar,
  SolarPanel,
  Bell, BellRing, BellOff, BellDot, BellElectric, Siren, AlarmClock,
  AlarmClockCheck, AlarmClockPlus, AlarmClockMinus, AlarmClockOff,
  AlarmCheck, AlarmPlus, AlarmMinus, AlarmSmoke,
  Lightbulb, LightbulbOff, Lamp, LampCeiling, LampDesk, LampFloor, LampWallDown, LampWallUp,
  Flashlight, FlashlightOff, Spotlight,
  Antenna, Satellite, SatelliteDish, RadioTower, Orbit,
  Barcode, QrCode,
  Radiation, Biohazard, FireExtinguisher,
  ShieldBan, ShieldClose,
  DoorClosed, DoorClosedLocked,
  PanelBottom, PanelBottomClose, PanelBottomOpen,
  PanelLeft, PanelLeftClose, PanelLeftOpen,
  PanelRight, PanelRightClose, PanelRightOpen,
  PanelTop, PanelTopClose, PanelTopOpen,
  LayoutDashboard, LayoutPanelLeft, LayoutPanelTop,
  Database, DatabaseBackup, DatabaseSearch,
  ServerCog, MonitorCog, MonitorCloud, MonitorDot, MonitorCheck,
  Cloud, CloudAlert, CloudBackup, CloudCheck, CloudCog, CloudDownload, CloudUpload, CloudSync, CloudOff,
  Terminal, TerminalSquare, Shell, Command,
  Code, Code2, CodeXml, CodeSquare,
  Binary,
  Map, MapPin, MapPinned, MapPlus, MapMinus, Compass,
  Clock, ClockAlert, ClockCheck, Timer, TimerOff, TimerReset,
  CalendarClock, CalendarCog, History,
  Layers, Layers2, Layers3, Component,
  Mail, Inbox, MessageCircle, MessageSquare,
  Phone, PhoneCall, PhoneIncoming, PhoneOutgoing,
  Send, AtSign,
  Video, VideoOff, Camera, CameraOff,
  Music, Headphones, Speaker, Mic, MicOff,
  Network, Router, Bluetooth, BluetoothConnected, BluetoothOff, BluetoothSearching,
  TowerControl, ParkingMeter,
  Stamp, PenTool,
  Logs, LogIn, LogOut,
  Recycle,
  MemoryStick,
  BriefcaseConveyorBelt, InspectionPanel,
  BrainCircuit, BrainCog,
  SquircleDashed,
  Microwave, WashingMachine,
  Diameter, SquareTerminal,
  SquareStack,
  Pin, PinOff,
  BoxSelect,
  BoomBox,
  HousePlug,
} as const

export type LucideIconName = keyof typeof LUCIDE_MAP
