// lib/icons/lucide.ts
// This file re-exports all needed Lucide icons by name
// We dynamically resolve them to avoid importing 1000+ icons statically

import {
  ArrowUp, ArrowDown, ArrowLeft, ArrowRight,
  ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
  CornerUpLeft, CornerUpRight, CornerDownLeft, CornerDownRight,
  ChevronsUp, ChevronsDown, ChevronsLeft, ChevronsRight,
  ArrowUpRight, ArrowUpLeft, ArrowDownRight, ArrowDownLeft,
  Move, RefreshCw, RotateCw, RotateCcw,
  File, FileText, FilePlus, FileMinus, FileCheck, FileX,
  Folder, FolderOpen, FolderPlus, FolderMinus,
  Image, Images, FileImage, Upload, Download,
  Copy, Clipboard, ClipboardCopy, Archive, Package,
  User, Users, UserPlus, UserMinus, UserCheck, UserX,
  Shield, ShieldCheck, ShieldAlert, Lock, Unlock, Key,
  Square, SquareCheck, CheckSquare, XSquare, MinusSquare, PlusSquare,
  Triangle, Circle, Hexagon, Octagon, Pentagon, Cross,
  Play, Pause, SkipBack, SkipForward, Rewind, FastForward,
  Volume, Volume1, Volume2, VolumeX,
  Maximize, Minimize, ZoomIn, ZoomOut, Focus,
  Sliders, Gauge,
  Home, Settings, Search, Menu, Grid, List,
  MoreHorizontal, MoreVertical,
  X, Check, CheckCircle, Plus, Minus, CircleDot,
  Crosshair, MousePointer, Pointer,
  Cpu, Monitor, Server, HardDrive, Printer, Tablet,
  Smartphone, Laptop, Wifi, Plug, PlugZap,
  Battery, BatteryCharging, BatteryFull, Radar, Tv,
  Thermometer, Droplet, Wind, Waves, Flame,
  Eye, EyeOff, Scan, ScanLine, Radio,
  Signal, Activity,
  Divide, Equal, Percent, Hash, Sigma, Pi,
  Aperture,
  BarChart, BarChart2, BarChart3,
  LineChart, PieChart, AreaChart,
  TrendingUp, TrendingDown,
  ScatterChart, ChartNoAxesCombined,
  FlaskConical, Beaker, TestTube,
  Atom, Dna, Microscope, Telescope,
  Mail, Inbox, MessageCircle, MessageSquare,
  Phone, PhoneCall, PhoneIncoming, PhoneOutgoing,
  Send, Bell, BellRing, BellOff, AtSign,
  Video, VideoOff, Camera, CameraOff,
  Music, Headphones, Speaker, Mic, MicOff,
} from 'lucide-react'

// Named export map for dynamic access
export const LUCIDE_MAP = {
  ArrowUp, ArrowDown, ArrowLeft, ArrowRight,
  ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
  CornerUpLeft, CornerUpRight, CornerDownLeft, CornerDownRight,
  ChevronsUp, ChevronsDown, ChevronsLeft, ChevronsRight,
  ArrowUpRight, ArrowUpLeft, ArrowDownRight, ArrowDownLeft,
  Move, RefreshCw, RotateCw, RotateCcw,
  File, FileText, FilePlus, FileMinus, FileCheck, FileX,
  Folder, FolderOpen, FolderPlus, FolderMinus,
  Image, Images, FileImage, Upload, Download,
  Copy, Clipboard, ClipboardCopy, Archive, Package,
  User, Users, UserPlus, UserMinus, UserCheck, UserX,
  Shield, ShieldCheck, ShieldAlert, Lock, Unlock, Key,
  Square, SquareCheck, CheckSquare, XSquare, MinusSquare, PlusSquare,
  Triangle, Circle, Hexagon, Octagon, Pentagon, Cross,
  Play, Pause, SkipBack, SkipForward, Rewind, FastForward,
  Volume, Volume1, Volume2, VolumeX,
  Maximize, Minimize, ZoomIn, ZoomOut, Focus,
  Sliders, Gauge,
  Home, Settings, Search, Menu, Grid, List,
  MoreHorizontal, MoreVertical,
  X, Check, CheckCircle, Plus, Minus, CircleDot,
  Crosshair, MousePointer, Pointer,
  Cpu, Monitor, Server, HardDrive, Printer, Tablet,
  Smartphone, Laptop, Wifi, Plug, PlugZap,
  Battery, BatteryCharging, BatteryFull, Radar, Tv,
  Thermometer, Droplet, Wind, Waves, Flame,
  Eye, EyeOff, Scan, ScanLine, Radio,
  Signal, Activity,
  Divide, Equal, Percent, Hash, Sigma, Pi,
  Aperture,
  BarChart, BarChart2, BarChart3,
  LineChart, PieChart, AreaChart,
  TrendingUp, TrendingDown,
  ScatterChart, ChartNoAxesCombined,
  FlaskConical, Beaker, TestTube,
  Atom, Dna, Microscope, Telescope,
  Mail, Inbox, MessageCircle, MessageSquare,
  Phone, PhoneCall, PhoneIncoming, PhoneOutgoing,
  Send, Bell, BellRing, BellOff, AtSign,
  Video, VideoOff, Camera, CameraOff,
  Music, Headphones, Speaker, Mic, MicOff,
} as const

export type LucideIconName = keyof typeof LUCIDE_MAP